### ISSUE TITLE
リポジトリを削除する

### ISSUE THREAD

**Issue by momeemt** [abap34/this-is-practice-repository-removed-soon#1]
人を勝手にco-authorに入れて実験しないでください

**Comment by abap34** [comment]
OSSなのでPRはいつでもWelcomeです

**Comment by momeemt** [comment]
適切にライセンスされていないソフトウェアをOSSと呼ぶことには疑問があります

**Comment by abap34** [comment]
fixed by #2

**Comment by momeemt** [comment]
ご対応いただきありがとうございます

**Comment by abap34** [comment]
閉じていいですか？

**Comment by momeemt** [comment]
リポジトリが削除された後にcloseされるべきだと思います

**Comment by abap34** [comment]
![image](https://github.com/abap34/this-is-practice-repository-removed-soon/assets/53076594/fc6c1666-e2d6-4592-bfcf-47c08098029a)
